server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/OnGiuaKyKienTrucUserDepartment/git-config-server
          default-label: master
          clone-on-start: true
        bootstrap: false